apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-speaker-service
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: {{ .Values.service.name }}
  selector:
    app: {{ template "fullname" . }}-speaker-service
