apiVersion: v1
kind: Service
metadata:
  name: confy-database
  labels:
    app: confy
    role: database
spec:
  ports:
    # the port that this service should serve on
  - port: 5432
    targetPort: 5432
  selector:
    app: confy
    role: database
